version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - pdf

python:
  install:
    # Install our python package, with a Keras backend, before building the docs
    - method: pip
      path: .
      extra_requirements:
        - jax
    - requirements: docs/requirements.txt
