version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    pre_build:
      - sphinx-apidoc -o docs/_autodoc nnodely
      - |
        mkdir -p docs/_autodoc/tutorials
        if [ ! -L docs/_autodoc/tutorials/examples ]; then
          ln -s nnodely/examples docs/_autodoc/tutorials/examples
          echo "Symlink created: docs/_autodoc/tutorials/examples -> nnodely/examples"
        else
          echo "Symlink already exists"
        fi


sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf

python:
  install:
    # Install our python package before building the docs
    - method: pip
      path: .
    - requirements: docs/requirements.txt


