[build-system]
requires = ["uv_build>=0.11.6,<0.12.0"]
build-backend = "uv_build"

[project]
name = "nnodely"
version = "1.5.5.dev1"
description = "Model-structured neural network framework for the modeling and control of physical systems"
readme = "README.md"
requires-python = ">=3.10,<3.14"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Gastone Pietro Rosati Papini", email = "tonegas@gmail.com" },
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  "graphviz>=0.21",
  "keras>=3.12.1",
  "matplotlib>=3.10.8",
  "numpy>=1.26.4",
  "pandas>=2.3.3",
  "tensorflow>=2.21.0",
  "tqdm>=4.67.3",
]

[project.optional-dependencies]
torch = ["torch>=2.2.2"]
jax = ["jax>=0.6.2"]

[project.urls]
"Homepage" = "https://github.com/tonegas/nnodely"
"Repository" = "https://github.com/tonegas/nnodely"

[dependency-groups]
dev = [
  "pre-commit>=4.5.1",
  "pyright>=1.1.408",
  "pytest-cov>=7.1.0",
  "ruff>=0.15.10",
  "tf2onnx>=1.17.0",
]

[tool.pyright]
pythonVersion = "3.10"
typeCheckingMode = "standard"

[tool.ruff]
target-version = "py310"

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "-ra"
